name: Github Action 실행시켜보기

on:
  push:
    branches:
      - main

#여러개의 Job 으로 이루어 질 수 있다.
jobs:
  My-Deploy-Job: # 이름을 붙인것
    runs-on: ubuntu-latest
    #하나의 Job 은 여러개의 Step 으로
    steps:
      - name: Hellow World 출력하기 # 이름을 붙인것
        run: echo "Hello World"

      - name: 여러 명령어 문장 작성하기
        run: |
          echo "Good"
          echo "Morning"          
          ls
      - name: Github Actions 자체 저장되어 있는 변수 사용해보기
        run: | # 레포지토리 이름 / 커밋 아이디
          echo $GITHUB_REPOSITORY
          echo $GITHUB_SHA
      - name: Github Actions Secret 변수 사용해보기
        run: |
          echo ${{ secrets.MY_NAME }}
          echo ${{ secrets.MY_HOBBY }}
